In [7]:
import numpy as np
import nnfs
def spiral_data(points, classes):
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points)  # radius
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y


nnfs.init()

X = [[1, 2, 3, 2.5]
    , [2.0, 5.0, -1.0, 2.0]
    , [-1.5, 2.7, 3.3, -0.8]]

X,y = spiral_data(100, 3)


In [8]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [9]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
    def backward(self, dvalues):
        self.dinputs = dvalues.copy()
        self.dinputs[self.inputs <= 0] = 0

In [12]:
layer1 = Layer_Dense(2, 5)
activation1 = Activation_ReLU()
layer1.forward(X)
#print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)


[[0.         0.         0.         0.         0.        ]
 [0.00080872 0.         0.00066663 0.         0.00080433]
 [0.00190606 0.         0.00169781 0.         0.        ]
 ...
 [0.         0.07141541 0.         0.09633921 0.2921411 ]
 [0.         0.14170745 0.         0.12578925 0.23655823]
 [0.         0.05355264 0.         0.08881066 0.30603167]]
