In [15]:
import numpy as np
np.random.seed(0)
X = [[1, 2, 3, 2.5]
    , [2.0, 5.0, -1.0, 2.0]
    , [-1.5, 2.7, 3.3, -0.8]]

In [18]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [20]:
layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)
layer1.forward(X)
layer2.forward(layer1.output)
print(layer1.output)
print(layer2.output)
# The output of layer1 is a 3x5 matrix, and the output of layer2 is a 3x2 matrix.
# The weights and biases are initialized randomly, so the output will vary each time you run the code.


[[-0.30606365 -0.46342184 -0.11883445 -0.98963701 -0.00915226]
 [ 0.02196248 -0.17944524  0.222946   -0.5621189  -0.19436056]
 [ 0.06020012 -0.0283124  -0.14707267 -0.49126153 -0.03931779]]
[[0.00656412 0.11864843]
 [0.04512981 0.03862067]
 [0.03924974 0.04256008]]
